arb-dir: lib/src/l10n/arb
output-dir: lib/src/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
untranslated-messages-file: untranslated-messages-file.txt